spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 4759
        url: jdbc:mysql://localhost:3306/pathfinder?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
#        open-in-view: false
#        properties:
#            hibernate:
#                format_sql: true
#                globally_quoted_identifiers: true
#    mvc:
#        hidden-method:
#            filter:
#                enabled: true
        sql:
            init:
                mode: always
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 5MB
